colorScheme = "avocado"
defaultAppearance = "dark"
autoSwitchAppearance = false
enableCodeCopy = true


[header]
layout = "hamburger"

[homepage]
layout = "profile"
showRecent = true

[footer]
showThemeAttribution = false
showCopyright = true
showScrollToTop = true
